version: '3'

services:
  dokuwiki:
    container_name: dokuwiki
    build: .
    ports:
      - "80:80"
    volumes:
      - "dokuwiki_data:/var/www/html"
volumes:
  dokuwiki_data:
    driver: local
