---
# Source: dokuwiki/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tag1docs"
  labels:
    app.kubernetes.io/name: dokuwiki
    helm.sh/chart: dokuwiki-2018-04-22b
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2018-04-22b"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dokuwiki
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dokuwiki
        app.kubernetes.io/instance: release-name
    spec:
      volumes:
      - name: dokuwiki-data
        persistentVolumeClaim:
          claimName: "dokuiwiki-data-pvc"
      imagePullSecrets:
        - name: tag1consulting-tag1docbot-pull-secret
        
      containers:
        - name: dokuwiki
          image: "quay.io/tag1consulting/dokuwiki:centos7"
          imagePullPolicy: Always
          volumeMounts:
          - name: dokuwiki-data
            mountPath: /var/www/html
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 800m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 512Mi
            
