---
# Source: dokuwiki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "tag1docs"
  labels:
    app.kubernetes.io/name: dokuwiki
    helm.sh/chart: dokuwiki-2018-04-22b
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2018-04-22b"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dokuwiki
    app.kubernetes.io/instance: release-name
